### ISSUE TITLE
Unstable training

### ISSUE THREAD

**Issue by alwynmathew** [ClubAI/MonoDepth-PyTorch#1]
Results with `lr=1e-3`

Epoch 1:
![epoch001_disp_left](https://user-images.githubusercontent.com/26373373/41765613-35f2807a-7622-11e8-8634-89c4e4a8577b.jpg)
Epoch 2:
![epoch003_disp_left](https://user-images.githubusercontent.com/26373373/41765624-3afbf6d2-7622-11e8-8ffe-e508e35afc6f.jpg)
Epoch 5:
![epoch005_disp_left](https://user-images.githubusercontent.com/26373373/41765630-3d8d78e4-7622-11e8-86c9-2358a6491ce0.jpg)

Disparities are degrading as I train more.

**Comment by NikolasEnt** [comment]
Hello, @alwynmathew!
What data and hyperparameters do you use for training?
I'd like to reproduce the issue.

**Comment by alwynmathew** [comment]
I used exact same data and hyperparameters you have used in the demo [notebook](https://github.com/ClubAI/MonoDepth-PyTorch/blob/master/Monodepth.ipynb).

**Comment by NikolasEnt** [comment]
Ok, I'll examine it. There were some issues with the parameters.

Meanwhile you can play with our  pretrained [model](https://my.pcloud.com/publink/show?code=XZeFfj7Zxhn5c4pq5J5XzLeTLEdghQ4Kyhb7) - it was trained for 75 epochs with lr=1e-2;  batch=20 (You may try to learn with the parameters). Or a better [one](https://my.pcloud.com/publink/show?code=XZqwnj7ZXYTq3o6IBwRLGI8hhxDJpFgdX8FV) - it was trained for extra 35 epochs with lr=1e-4 (with the first model as pretrain).

**Comment by alwynmathew** [comment]
I have also ported original monodepth to pytorch [here](https://github.com/alwynmathew/monodepth-pytorch). I faced the exact same issue that the disparities get degraded after few epochs. What are the hyperparameters you used to get better results?

**Comment by NikolasEnt** [comment]
lr=1e-2; batch=20 is good enough (see above) for our implementation

**Comment by alwynmathew** [comment]
@NikolasEnt `batch_size`= 20 is too big.
Epoch 10 with `batch_size` = 8 and `lr=1e-2`
![epoch010_disp_left](https://user-images.githubusercontent.com/26373373/41775320-18995ab6-7641-11e8-952d-32db6ba45c01.jpg)
Epoch 16
![epoch016_disp_left](https://user-images.githubusercontent.com/26373373/41778703-2d97cab8-764d-11e8-8198-73c59cd34fbe.jpg)
Its still unstable.

**Comment by voeykovroman** [comment]
Hello, @alwynmathew!

Once again. Are you sure you downloaded correct dataset as described [here](https://github.com/ClubAI/MonoDepth-PyTorch#kittil)?
Because there are 38237 images and you attached your results for the first 10 epochs after approximately an hour after @NikolasEnt answered you about lr. And you used smaller batch size what means that you will need more time for training than we do while we needed something about 45 minutes for 1 epoch using single GTX1080 Ti. It looks like something wrong with your data or equipment.
During this week we will try to reproduce our training using exactly this repo without any changes downloaded on new machine and publish disparities we get after 10 epochs in this thread.

**Comment by alwynmathew** [comment]
Hi @Sparkling-Brick, according to the [notebook](https://github.com/ClubAI/MonoDepth-PyTorch/blob/master/Monodepth.ipynb) provided in the repo, the data loader is just loading from one of the kitti dataset subfolder `'data_dir':'../../2011_09_26/' `.

**Comment by voeykovroman** [comment]
Yes. Thanks for noting it, the path was changed to check whether notebook working or not before publishing. However if you noticed that path in the notebook is just for one subfolder you should be able to change it to load the whole dataset.
Moreover if you read our README you would notice the structure of data and path variable are described [here](https://github.com/ClubAI/MonoDepth-PyTorch#dataloader).

**Comment by alwynmathew** [comment]
But @Sparkling-Brick  do you think just added more data will solve the problem? The original implementation [used](https://github.com/mrharicot/monodepth/blob/master/monodepth_main.py#L37) batch size as small as 8, why do you recommend higher batch size?

**Comment by NikolasEnt** [comment]
Hi, @alwynmathew, we retrain our model from scratch with the following parameters:
```Python
'model':'resnet18_md',
'learning_rate':1e-2,
'batch_size':8,
'adjust_lr':True,
'do_augmentation':True,
'augment_parameters':[0.8, 1.2, 0.5, 2.0, 0.8, 1.2],
```

Here it is the result. Obviously, it should be trained further, however, it is stable with lr=1e-2 and batch size 8.
![demo](https://user-images.githubusercontent.com/13784667/42002116-d10a9f7a-7a6e-11e8-896c-d1dfa311b510.png)
Full Kitti dataset from the original [repo](https://github.com/mrharicot/monodepth) was utilized for training.

**Comment by alwynmathew** [comment]
@NikolasEnt thank you for you effort, I'll train with same parameters. 

Please modify your [KittiLoader](https://github.com/ClubAI/MonoDepth-PyTorch/blob/master/data_loader.py#L186) class to read all kitti images. The current version just look for subfolder `image_02/data/` and `image_03/data/ `inside `root_dir`which doesn't follow standard kitti directory structure. 
```
left_dir = os.path.join(root_dir, 'image_02/data/')
right_dir = os.path.join(root_dir, 'image_03/data/')

data
├── kitti
│   ├── image_02
│   │   ├─ data
│   │   │   ├── 0000000000.png
│   │   │   └── ...
│   ├── image_03
│   │   ├─ data
│   │   │   ├── 0000000000.png
│   │   │   └── ...
```

Instead it should look for all folder as [mentioned](https://github.com/ClubAI/MonoDepth-PyTorch#dataloader) in the readme.

```
data
├── kitti
│   ├── 2011_09_26_drive_0001_sync
│   │   ├── image_02
│   │   │   ├─ data
│   │   │   │   ├── 0000000000.png
│   │   │   │   └── ...
```

**Comment by alwynmathew** [comment]
Thank you @NikolasEnt  for the effort of training the model from scratch. 

I do get perfect disparity map for selected images but it doesn't seem to applies to all of the kitti test images even after training for 17 epoch with same parameters on full kitti dataset. 

```
'model':'resnet18_md',
'learning_rate':1e-2,
'batch_size':8,
'adjust_lr':True,
'do_augmentation':True,
'augment_parameters':[0.8, 1.2, 0.5, 2.0, 0.8, 1.2]
```

Is it just me or do you face the same problem?

Reconstructed images and corresponding disparities during my training:
![drawing](https://user-images.githubusercontent.com/26373373/42075050-b021d7e6-7b8c-11e8-92b9-1499de7791fa.png)

**Comment by NikolasEnt** [comment]
Hi, @alwynmathew. It looks like the second original raw image has some issues. They may be due to video->image transformation process or image encoding in the dataset. Personally, I didn't observe such examples, however, I didn't exam the whole dataset.
Ideally, such images should be excluded from train/val subsets.
