### ISSUE TITLE
Can't download pretrained model from link in README

### ISSUE THREAD

**Issue by seompark** [ClubAI/MonoDepth-PyTorch#12]
I tried to download pretrained models, but link was broken.

**Comment by askorikov** [comment]
Couldn't reproduce the issue - for me the link still works. I used [this one](https://my.pcloud.com/publink/show?code=XZb5r97ZD7HDDlc237BMjoCbWJVYMm0FLKcy).

**Comment by NikolasEnt** [comment]
For me it works as well too.
However, we'll consider to add mirror links in the future when we'll release more pretrained models.

**Comment by seompark** [comment]
I tried again, idk why but it works! Thx :D
