### ISSUE TITLE
Why Sigmoid?

### ISSUE THREAD

**Issue by sabetAI** [ClubAI/MonoDepth-PyTorch#13]
Why is a sigmoid operation used for the output map?

**Comment by voeykovroman** [comment]
We use sigmoid to squeeze output values into range between 0 and 1. These values are relative disparities between left and right images and need to be multiplied by image size to calculate, for example, depth of some point on the image.
Moreover we use 0.3 as a constraint to get some reasonable values as the original implementation suggested.
