### ISSUE TITLE
Question about Post-processing Code

### ISSUE THREAD

**Issue by zhanghang1989** [ClubAI/MonoDepth-PyTorch#17]
Thanks a lot for sharing the code. What is the post-processing code doing:
https://github.com/ClubAI/MonoDepth-PyTorch/blob/master/main_monodepth_pytorch.py#L109-L117

```python
def post_process_disparity(disp):
    (_, h, w) = disp.shape
    l_disp = disp[0, :, :]
    r_disp = np.fliplr(disp[1, :, :])
    m_disp = 0.5 * (l_disp + r_disp)
    (l, _) = np.meshgrid(np.linspace(0, 1, w), np.linspace(0, 1, h))
    l_mask = 1.0 - np.clip(20 * (l - 0.05), 0, 1)
    r_mask = np.fliplr(l_mask)
    return r_mask * l_disp + l_mask * r_disp + (1.0 - l_mask - r_mask) * m_disp
```

**Comment by NikolasEnt** [comment]
Hi, @zhanghang1989 
It implements post-processing on disparity maps, as described by authors in the original [paper](https://arxiv.org/pdf/1609.03677.pdf). See **Post-processing** paragraph in the section **4.1. Implementation Details**.
