### ISSUE TITLE
Endoscope images

### ISSUE THREAD

**Issue by YJonmo** [ClubAI/MonoDepth-PyTorch#18]
Hi, 

Thanks for the code. 
I am about to use this repo for training to be able to estimate the depth for the images acquired from a stereo endoscope under the water. As I can see this and most of the mono depth methods are applied for the street and cars. Is there anything that I should do or not to do for training the model when my aim is to get the depth for underwater and small distant objects?  

Also I noticed the amount of overlap between stereo images for me is not as much as typical images from the street views. So my problem is a smaller amount of the overlap. 

Thanks for reading

**Comment by NikolasEnt** [comment]
Hi, thank you for your interest.
Actually, it may be quite challenging to archive proper performance in case of scenes with a lot of texture-free regions. For instance, the Monodepth may produce some artifacts on a clear sky part of a photo. It may also overfit to your dataset as well. So, from my perspective, a lot of augmentations are essential for such a problem. Of course, you have to keep in mind that all images transformations should be correct to preserve a valid stereo pair. You may add artificial images (generated by computer graphics) to enrich the training dataset. It may also be beneficial to make sure that there is not a lot of "empty" images without any contrast objects visible. Probably, the CNN is sustainable to a smaller overlap of pictures in a stereo pair. However, it is hard to predict without trying.

Always keep experimenting! Feel free to share your results if you observe something interesting.

**Comment by YJonmo** [comment]
Thanks Nikola for replying. 

One question: how many images is good enough for trainig? I have got 4000, but I think I need more.

**Comment by NikolasEnt** [comment]
Well, it really depends on the dataset. For instance, if it is a sequence of consequent frames from a few videos - it is likely that it will be not enough. However, if it is a set of independent stereo photos which are quite similar to your test (production) scenes, it may be enough for training with augmentations. Actually, it is not possible to precisely answer the question without experimenting.
