### ISSUE TITLE
Test Data

### ISSUE THREAD

**Issue by olgapeled** [ClubAI/MonoDepth-PyTorch#19]
Thank you for your great work!!
Where can I find the test data used here? 

Is it the  Cityscapes dataset?
Kitti was only used for training?

**Comment by NikolasEnt** [comment]
Hi, thank you for your interest!

We used the [KITTI](http://www.cvlibs.net/datasets/kitti/raw_data.php) raw dataset only in order to replicate the learning process of the original authors repo. We used the following subset as a hold-out validation:
```
2011_09_26_drive_0002_sync  2011_09_29_drive_0071_sync
2011_09_26_drive_0014_sync  2011_09_30_drive_0033_sync
2011_09_26_drive_0020_sync  2011_10_03_drive_0042_sync
2011_09_26_drive_0079_sync
```

**Comment by olgapeled** [comment]
Thank you!
I see that some of the videos are in gray scale.

**Comment by voeykovroman** [comment]
It's not that some videos are in grayscale, just every archive consists from additional data so you can find processed grayscale stereo sequences (usually subfolders image_00 and image_01) as well as processed color stereo sequences (usually subfolders image_02 and image_03)
