### ISSUE TITLE
Doesnt follow standard kitti directory structure

### ISSUE THREAD

**Issue by alwynmathew** [ClubAI/MonoDepth-PyTorch#2]
The kitti directory structure given in the your [readme](https://github.com/ClubAI/MonoDepth-PyTorch#dataloader) seems to be incorrect.

Directory structure mentioned in your readme:
```
data
├── kitti
│   ├── 2011_09_26_drive_0001_sync
│   │   ├── image_02
│   │   │   ├─ data
│   │   │   │   ├── 0000000000.png
│   │   │   │   └── ...
│   │   ├── image_03
│   │   │   ├── data
│   │   │   │   ├── 0000000000.png
│   │   │   │   └── ...
│   ├── ...
```

Standard kitti directory structure as [mentioned](https://raw.githubusercontent.com/mrharicot/monodepth/master/utils/filenames/kitti_test_files.txt) in [mrharicot repo](https://github.com/mrharicot/monodepth/tree/master/utils/filenames) as below:

```
data
├── kitti
│   ├── 2011_09_30
│   │   ├── 2011_09_26_drive_0001_sync
│   │   │   ├── image_02
│   │   │   │   ├─ data
│   │   │   │   │   ├── 0000000000.png
│   │   │   │   │   └── ...
│   │   │   ├── image_03
│   │   │   │   ├─ data
│   │   │   │   │   ├── 0000000000.png
│   │   │   │   │   └── ...
│   │   ├── ...
│   ├── ...
```
Its not a big deal, still its good to follow the standard structure.

**Comment by voeykovroman** [comment]
@alwynmathew Thanks for mentioning it. We left with this structure because of convenience reasons as the main data folder after downloading the whole dataset contains only archives like "2011_09_26_drive_0001_sync".
