### ISSUE TITLE
How do you compute L-R Consistency

### ISSUE THREAD

**Issue by hurricane2018** [ClubAI/MonoDepth-PyTorch#25]
# L-R Consistency
        right_left_disp = [self.generate_image_left(disp_right_est[i],
                           disp_left_est[i]) for i in range(self.n)]
        left_right_disp = [self.generate_image_right(disp_left_est[i],
                           disp_right_est[i]) for i in range(self.n)]

        # L-R Consistency
        lr_left_loss = [torch.mean(torch.abs(right_left_disp[i]
                        - disp_left_est[i])) for i in range(self.n)]
        lr_right_loss = [torch.mean(torch.abs(left_right_disp[i]
                         - disp_right_est[i])) for i in range(self.n)]
        lr_loss = sum(lr_left_loss + lr_right_loss)

Can you explain how did you compute it?

**Comment by askorikov** [comment]
The quoted code is exactly how we compute it, so I don't understand what the question is.
