### ISSUE TITLE
How can I get deep information? 

### ISSUE THREAD

**Issue by caikw0602** [ClubAI/MonoDepth-PyTorch#29]
Very thank you for your good job. I have studied for several days. I think the output of this code is only the disparities and dispariteis with post-processing. Am I ritht? If so, how can I get the deep information of my own input pics please? Look forward to your reply. Thank you very much.

**Comment by ltshan** [comment]
It should be B * f / disparity

**Comment by askorikov** [comment]
Yes, also see: https://stackoverflow.com/a/61054845/11968043
