### ISSUE TITLE
disparity map error

### ISSUE THREAD

**Issue by YunYang1994** [ClubAI/MonoDepth-PyTorch#30]
hi, thanks for your impressive work, which helps me a lot. but I met the following problem and I have no idea about it. Can you give me some points to solve it ?

![0000000012](https://user-images.githubusercontent.com/30433053/76438366-dd59ab00-63f5-11ea-8cc9-61ed50611dc8.jpg)

thanks in advance!

**Comment by alwynmathew** [comment]
This is a known issue and has been mentioned in the [monodepth paper](https://arxiv.org/pdf/1609.03677.pdf) under Section 4.1 Implementation Details under Post-processing as "effect of stereo disocclusions ". This is why Godard has introduced a post-processing (**pp**) step in his experiments.
