### ISSUE TITLE
[Question] How to get the metric disparity value? 

### ISSUE THREAD

**Issue by CaptainEven** [ClubAI/MonoDepth-PyTorch#31]
Thanks for your great work！As i noticed that the output of the network is sigmod modulated values lie in [0, 1], so how to get the actual value of disparity?

**Comment by askorikov** [comment]
Thanks! The disparity is returned as a fraction of the image width. So to get the disparity value in pixels you should multiply the network output by the image width.

**Comment by CaptainEven** [comment]
@askorikov Thanks for the quick reply, multiply the pre-defined input network image width like (512 by default) right?

**Comment by askorikov** [comment]
Yes, exactly.
