### ISSUE TITLE
[Feature requested] Support for depth-separable(depth-wise) backbones such as MobileNetV2, EfficientNet...

### ISSUE THREAD

**Issue by CaptainEven** [ClubAI/MonoDepth-PyTorch#32]
Thank you for your excellent work! I want to deploy MonoDepth to an embedding chip(Horizon X3) which is computational efficient on backbones for depth-separable structure. I will appreciate if such a backbone network is provided!

**Comment by NikolasEnt** [comment]
Hello @CaptainEven. Thank you for your interest. The project is just an academic paper implementation which doesn't suggest other backbones.
