### ISSUE TITLE
Key already registered with the same priority: GroupSpatialSoftmax

### ISSUE THREAD

**Issue by Entretoize** [ClubAI/MonoDepth-PyTorch#35]
Hello, I trying to test your project that seems very nice, but I can't find how to run a simple test, I tried that:

`main_monodepth_pytorch.py --data_dir=test --model_path=models/monodepth_resnet18_001.pth --output_directory=output --input_height=375 --input_width=1242 --model=resnet18 --mode=test --input_channels=3 --num_workers=4
`
But I get that error: `Key already registered with the same priority: GroupSpatialSoftmax`
What does that mean ? What can I do ?

Thanks in advance !

**Comment by voeykovroman** [comment]
Hi! Thanks for your interest in our project. Most likely there is a problem with your PyTorch installation. Please, check this thread: https://discuss.pytorch.org/t/importerror-key-already-registered-with-the-same-priority/86271/2
