### ISSUE TITLE
Does this work on stereo image pair (not video)

### ISSUE THREAD

**Issue by Karric** [ClubAI/MonoDepth-PyTorch#36]
Will this produce decent results with just left/right static images? I'm trying to find a library that can do that, but so far the ones I've found and tried produce awful results.

**Comment by voeykovroman** [comment]
Well, the demo you can see in the README was produced only using left (or right) subsequent frames, so the model was able to provide a decent depth estimation using only one static image (that's the idea behind the paper to use only one image on inference for depth estimation, stereo-images are used only to train the model). But please keep in mind that pretrained model was trained on a KITTI dataset, so it is aimed to work with images captured from a driving car.

**Comment by Karric** [comment]
@voeykovroman thanks for the reply. I'm looking at the readme closely and I'm not seeing any pretrained model links. Would it be possible for the author to share a pretrained model?

**Comment by voeykovroman** [comment]
Please check this abstract https://github.com/OniroAI/MonoDepth-PyTorch#train-results-and-pretrained-model
Link may be found inside
