### ISSUE TITLE
Provided model fails to load

### ISSUE THREAD

**Issue by stashvala** [ClubAI/MonoDepth-PyTorch#9]
I tried to run the model you uploaded [here](https://my.pcloud.com/publink/show?code=XZdFzu7ZfCAEf0uj8zRhDrBsjuEoeSo2QXak) with parameters

`python3 main_monodepth_pytorch.py --mode test --model "resnet18_md" --input_channels 3 --data_dir "dataset/" --model_path trained_kitti_model.pth --output_directory out 
`
But i got the following error

`Traceback (most recent call last):
  File "main_monodepth_pytorch.py", line 321, in <module>
    main()
  File "main_monodepth_pytorch.py", line 316, in main
    model_test = Model(args)
  File "main_monodepth_pytorch.py", line 145, in __init__
    self.model.load_state_dict(torch.load(args.model_path))
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 719, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Resnet18_md:
	size mismatch for iconv3.conv_base.weight: copying a param of torch.Size([64, 130, 3, 3]) from checkpoint, where the shape is torch.Size([64, 128, 3, 3]) in current model.
	size mismatch for iconv2.conv_base.weight: copying a param of torch.Size([32, 98, 3, 3]) from checkpoint, where the shape is torch.Size([32, 96, 3, 3]) in current model.
`

I removed + 2 in Resnet18_md
`self.iconv3 = conv(64+64 + 2, 64, 3, 1)`
and
`self.iconv2 = conv(64+32 + 2, 32, 3, 1)`

Model then loads but on forward pass I get this error

`Traceback (most recent call last):
  File "main_monodepth_pytorch.py", line 321, in <module>
    main()
  File "main_monodepth_pytorch.py", line 317, in main
    model_test.test()
  File "main_monodepth_pytorch.py", line 298, in test
    disps = self.model(left)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/stas/gits/MonoDepth-PyTorch/models_resnet.py", line 297, in forward
    iconv3 = self.iconv3(concat3)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/stas/gits/MonoDepth-PyTorch/models_resnet.py", line 19, in forward
    x = self.conv_base(F.pad(x, p2d))
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size [64, 128, 3, 3], expected input[2, 130, 130, 66] to have 128 channels, but got 130 channels instead
`

Could you update the uploaded model, code or maybe tell me what I'm doing wrong? Thanks

Python version 3.6.5, Pytorch version 0.4.1

**Comment by NikolasEnt** [comment]
Yes, you are right, we are currently updating the model after fixing several bugs in architecture. That is why, the provided model weights should not fit the model.
We will update the provided model as soon as possible. I apologize for the inconvenience.

**Comment by stashvala** [comment]
No problem, just wanted to try out the model. I also had to switch torch.Resize to torch.Scale in [transforms.py](https://github.com/ClubAI/MonoDepth-PyTorch/blob/master/transforms.py#L34). Thanks for the quick response, good luck with fixing!

**Comment by xiaohedu** [comment]
> Yes, you are right, we are currently updating the model after fixing several bugs in architecture. That is why, the provided model weights should not fit the model.
> We will update the provided model as soon as possible. I apologize for the inconvenience.

look forward to updating as soon as possible

**Comment by voeykovroman** [comment]
@xiaohedu We will provide pretrained model in a couple days. But until that you can try to train this model yourself if you have KITTI dataset.

**Comment by xiaohedu** [comment]
> @xiaohedu We will provide pretrained model in a couple days. But until that you can try to train this model yourself if you have KITTI dataset.
thank you.

**Comment by voeykovroman** [comment]
While we are training a new model (have technical issues, probably takes one more week) you can switch to commit **566403987b16034122f7620c11d23386fe215ce6** and use our old model provided in README (demo video in README was made using exactly this model).
But for correct work you should replace ImageLoader with KittiLoader in main_monodepth_pytorch.py in line 160. And also make relevant changes in paths to images and to model in demo notebook.

**Comment by NikolasEnt** [comment]
@stashvala @xiaohedu Ok, we updated the code in the master branch, fixed several bugs and provided a new pretrained model along with the updated jupyter notebook for the training recreation. Hope, it helps.
